### ISSUE TITLE
Parsing dhcp-leases file?

### ISSUE THREAD

**Issue by jbod429** [npotts/go-dhcpd-leases#2]
Hello NPotts,
Thanks for your code, this has helped me to understand the parsing a little more.

I am having an issue building and running your code, and I'm still Noob of Go, so I didn't understand how to parse the file (dhcpd.leases) completely.
You wrote in the readme:
 f, err := os.Open("/var/lib/dhcpd/dhcpd.leases")
    leases := Parse(f)
    ...

I've tried adding this to a main func and out of one several different ways and haven't had any luck. I also merged the 2 lease.go and parser.go into one.

How does the full file look when/if merged into one file, and how do you get the parse to read the leases file?

Excuse my misunderstanding, and thanks for sharing your project.

**Comment by nijave** [comment]
```
package main

import (
	"fmt"
	"github.com/npotts/go-dhcpd-leases"
	"os"
	"strings"
)

func main() {
	f, err := os.Open("./dhcpd.leases")
	if err != nil {
		panic(err)
	}

	leaseData := leases.Parse(f)

	for _, lease := range leaseData {
		if lease.BindingState != "active" || len(lease.ClientHostname) < 3 {
			continue
		}
		fmt.Printf("%-16s %s\n", lease.IP.String(), strings.ToLower(lease.ClientHostname))
	}
}
```

**Comment by npotts** [comment]
@nijave  is correct on this.  I should have been a bit more explicit.  I took his code and commented on what is going on.

```go

package main

import (
	"fmt"
	leases "github.com/npotts/go-dhcpd-leases"
	"os"
	"strings"
)

func main() {
        // this opens some file named 'dhcpd.leases' in your current dir 
	f, err := os.Open("./dhcpd.leases")
        //if unable to open for any reason (non-file, permissions, etc), exit with an error
	if err != nil { 
		panic(err)
	}
        //this is where this library is used. It reads
        // from the *File named "f", but it could be any sort of io.Reader
	leaseData := leases.Parse(f)
        //print out what was loaded
	for _, lease := range leaseData {
		if lease.BindingState != "active" || len(lease.ClientHostname) < 3 {
			continue
		}
		fmt.Printf("%-16s %s\n", lease.IP.String(), strings.ToLower(lease.ClientHostname))
	}
}
```
